user deactivate flow
ELEVATE-Project/user pull request #211
Opened 2023-11-06 10:05 UTC by adithyadinesh0412

2023-11-06 15:59 UTC, rakeshSgr commented on src/services/helper/account.js
> +			// await utilsHelper.redisDel(email)
@adithyadinesh0412 is this line required?

2023-11-06 16:00 UTC, rakeshSgr commented on src/services/helper/account.js
> +			if (userRedisData && userRedisData.action == 'deactivateUser' && userRedisData.otp == bodyData.otp) {
@adithyadinesh0412  action should come from common config  'deactivateUser'

2023-11-06 16:02 UTC, rakeshSgr commented on src/services/helper/account.js
> +			if (userData && userData.action === 'deactivateUser') {
@adithyadinesh0412 get action 'deactivateUser' from common config

2023-11-06 16:04 UTC, rakeshSgr commented on src/services/helper/account.js
> +				if (res !== 'OK') {
@adithyadinesh0412 get response code from  common response code

2023-11-06 16:05 UTC, rakeshSgr commented on src/controllers/v1/account.js
> +	async generateDisableOtp(req) {
@adithyadinesh0412 method details are missing

2023-11-09 09:25 UTC, rakeshSgr commented on src/controllers/v1/account.js
> +	async generateDisableOtp(req) {
@adithyadinesh0412 there is an existing generateOtp function can we use that function ?

2023-11-09 09:27 UTC, rakeshSgr commented on src/services/helper/account.js
> +				otp = Math.floor(Math.random() * 900000 + 100000) // 6 digit otp
@adithyadinesh0412 please do the generic method for generating the otp

2023-11-09 09:32 UTC, ankitpws requested changes
Reviewed on 9 Nov 3

2023-11-09 09:32 UTC, ankitpws commented on src/database/migrations/20230531105847-create-users-table.js
> +			status_updated_at: {
create new migration for this changes @adithyadinesh0412

2023-11-09 09:32 UTC, ankitpws commented on src/migrations/20220722162957-notificationTemplates.js
> +	{
dont update in migration

2023-11-09 09:32 UTC, ankitpws commented on src/.env.sample
> +REGISTRATION_EMAIL_TEMPLATE_CODE=registration
Why additional ENV variables added and if added then templets are missing

2023-11-10 16:46 UTC, adithyadinesh0412 commented on src/.env.sample
> +REGISTRATION_EMAIL_TEMPLATE_CODE=registration
template also added in seeders. @ankitpws

2023-11-10 16:47 UTC, adithyadinesh0412 commented on src/controllers/v1/account.js
> +	async generateDisableOtp(req) {
added a generic function in generics/utils

2023-11-14 08:55 UTC, ankitpws requested changes
Reviewed ON 14 Nov

2023-11-14 08:55 UTC, ankitpws commented on src/generics/utils.js
> +	// Generate a random 6-digit number
generate OTP can be normal function why email ID is needed @adithyadinesh0412

2023-11-14 08:55 UTC, ankitpws commented on src/services/account.js
> +				const redisData = utils.generateOtp(6, bodyData.email.toLowerCase(), common.deactivateAction)
get OTP from utils and prepare data here @adithyadinesh0412

2023-11-14 11:50 UTC, ankitpws approved these changes
Approved ON 14 Nov 5:20PM

2024-01-09 09:13 UTC, closed without merging