Added Event For Organization Extension Creation
ELEVATE-Project/user pull request #356
Opened 2024-01-21 17:41 UTC by joffinjoy

2024-01-22 03:37 UTC, aks30 requested changes
Reviewed on 22 Jan

2024-01-22 03:37 UTC, aks30 commented on src/constants/eventEndpoints.js
> +		createOrganizationExtension: [
@joffinjoy did we not confirm that all complete URLs can be given via envs? And multiple URLs for same event can be there?

2024-01-22 17:57 UTC, joffinjoy commented
New envs:

EVENT_GROUP_ORGANIZATION='organizationEvents'
EVENTS_ALLOWED_ARGS='updated_at,created_at,update_by,created_by'
EVENT_TYPE_CREATE='update'
EVENT_TYPE_UPDATE='create'
EVENT_TYPE_DELETE='delete'
EVENT_ENTITY_ORGANIZATION='organization'

2024-01-30 07:28 UTC, joffinjoy commented on src/.env.sample
> +EVENTS_ALLOWED_ARGS='updated_at,created_at,update_by,created_by'
Move to hardcode

2024-01-30 07:28 UTC, joffinjoy commented on src/.env.sample
> +EVENT_TYPE_DELETE='delete'
Remove these ENVs

2024-01-30 07:32 UTC, joffinjoy commented on src/dtos/eventBody.js
> +			throw new Error('Entity, EventType & EntityId values are mandatory for an Event')
This shouldn't throw the error to the caller.

2024-02-01 06:39 UTC, rakeshSgr commented on src/.env.sample
> +EVENT_ORG_LISTENER_URLS='http://interface:3567/mentoring/v1/organization/eventListener'
@joffinjoy can we divide this into two parts, base URL  and endpoint

2024-02-01 06:44 UTC, joffinjoy commented on src/.env.sample
> +EVENT_ORG_LISTENER_URLS='http://interface:3567/mentoring/v1/organization/eventListener'
Akash wanted the full paths separated by commas.

2024-02-01 06:52 UTC, rakeshSgr commented on src/.env.sample
> +EVENT_ORG_LISTENER_URLS='http://interface:3567/mentoring/v1/organization/eventListener'
@joffinjoy I'm thinking, endpoints can be in common it won't change most of the time

2024-02-01 06:52 UTC, rakeshSgr commented on src/generics/form.js
> +//const utils = require('@generics/utils')
@joffinjoy can you remove unwanted code

2024-02-01 09:05 UTC, joffinjoy commented on src/generics/form.js
> +//const utils = require('@generics/utils')
Can we keep it for now. The thing is, we need this code to use the caching itself. But in current form, introducing caching will introduce circular dependency. I will look into this issue as a separate one. Just want to retain this form for that.

2024-02-01 10:00 UTC, merged