Adding Skip Validation for updating User
ELEVATE-Project/user pull request #526
Opened 2024-07-03 09:33 UTC by sumanvpacewisdom

2024-07-03 09:45 UTC, rakeshSgr commented on src/services/user.js
> +		let skipValidation = true
@sumanvpacewisdom is it internal API ?

2024-07-03 10:50 UTC, nevil-mathew commented on src/services/user.js
> +		let skipValidation = true
Can you rename 'skipValidation' to 'skipRequiredValidation'

2024-07-03 10:50 UTC, nevil-mathew commented on src/generics/utils.js
Are we not adding the changes needed for session apis ?

2024-07-05 12:14 UTC, aks30 requested changes
Reviewed

2024-07-05 12:14 UTC, aks30 commented on src/services/user.js
> +			const filter = {
We should only query the language entity type no?

2024-07-05 12:14 UTC, aks30 commented on src/services/user.js
> +			delete processDbResponse.refresh_tokens
Why so much unnecessary code?

2024-07-05 12:14 UTC, aks30 commented on src/validators/v1/user.js
> +			.isIn(['en', 'hi'])
This doesn't make sense, tomorrow more lanugages can be added from entity type

2024-07-05 12:17 UTC, sumanvpacewisdom commented on src/validators/v1/user.js
> +			.isIn(['en', 'hi'])
@aks30 this is the existing code and i have just aligned separately

2024-07-05 12:23 UTC, sumanvpacewisdom commented on src/services/user.js
> +			delete processDbResponse.refresh_tokens
@aks30 
This is the same code for updating the user they have used

2024-07-05 14:02 UTC, aks30 requested changes
Reviewed on 5 July 7:30 PM

2024-07-05 14:02 UTC, aks30 commented on src/validators/v1/user.js
> +			.isIn(['en', 'hi'])
But its not valid.

2024-07-05 14:02 UTC, aks30 commented on src/services/user.js
> +			delete processDbResponse.refresh_tokens
But what if we don't do here.

2024-07-05 14:07 UTC, sumanvpacewisdom commented on src/validators/v1/user.js
> +			.isIn(['en', 'hi'])
OK will remove .
@aks30

2024-07-08 04:49 UTC, rakeshSgr commented on src/controllers/v1/user.js
> +	 * @name update
@sumanvpacewisdom change the method name

2024-07-08 04:50 UTC, rakeshSgr commented on src/controllers/v1/user.js
> +	 * @returns {JSON} - user updated data.
@sumanvpacewisdom update the return response message

2024-07-08 05:28 UTC, rakeshSgr commented on src/database/migrations/20240705115500-update_required_column_EntityTypes.js
> +		const valuesToUpdate = ['languages', 'location']
@sumanvpacewisdom only two columns ?

2024-07-08 05:42 UTC, rakeshSgr commented on src/services/user.js
> +	 * @name update
@sumanvpacewisdom update method name

2024-07-08 05:43 UTC, rakeshSgr commented on src/services/user.js
> +	 * @returns {JSON} - updated user response
@sumanvpacewisdom update the proper response

2024-07-08 05:46 UTC, rakeshSgr commented on src/services/user.js
> +		bodyData.updated_at = new Date().getTime()
@sumanvpacewisdom move this line to below when you are going to update, its not require in failure cases

2024-07-08 05:46 UTC, rakeshSgr commented on src/services/user.js
> +				status: 'ACTIVE',
@sumanvpacewisdom use common constants

2024-07-08 05:48 UTC, rakeshSgr commented on src/services/user.js
> +				value: 'preferred_language',
@sumanvpacewisdom will it be a constant?

2024-07-08 05:49 UTC, rakeshSgr commented on src/services/user.js
> +			let res = utils.validateInput(bodyData, prunedEntities, userModel, skipRequiredValidation)
@sumanvpacewisdom use proper naming convention

2024-07-08 05:50 UTC, rakeshSgr commented on src/services/user.js
> +			//validationData = utils.removeParentEntityTypes(JSON.parse(JSON.stringify(validationData)))
@sumanvpacewisdom remove  commented lines if not required

2024-07-08 05:51 UTC, rakeshSgr commented on src/services/user.js
> +					message: 'SESSION_CREATION_FAILED',
@sumanvpacewisdom are we creating session here ?

2024-07-08 05:57 UTC, rakeshSgr commented on src/services/user.js
> +				result: processDbResponse,
@sumanvpacewisdom change the response message to specific to prefered language settings

2024-07-08 05:58 UTC, rakeshSgr commented on src/services/user.js
> +			delete processDbResponse.refresh_tokens
@sumanvpacewisdom just make the common method to delete un necessary fields before sending to response. 
Create function and use it here, we can make use later

2024-07-08 06:00 UTC, rakeshSgr commented on src/validators/v1/user.js
> +		req.checkBody('preferred_language')
@sumanvpacewisdom is it mandatory ? then validate it

2024-07-08 06:01 UTC, rakeshSgr commented on src/controllers/v1/user.js
> +	async setLanguagePreference(req) {
@sumanvpacewisdom api-doc changes are missing

2024-07-08 07:00 UTC, sumanvpacewisdom commented on src/database/migrations/20240705115500-update_required_column_EntityTypes.js
> +		const valuesToUpdate = ['languages', 'location']
We have three , and we don't have language preferences to be validated while updating user ,so we are making only 2 entityTypes as true

2024-07-08 07:06 UTC, sumanvpacewisdom commented on src/services/user.js
> +				value: 'preferred_language',
@rakeshSgr not it cannot be

2024-07-08 07:39 UTC, sumanvpacewisdom commented on src/validators/v1/user.js
> +		req.checkBody('preferred_language')
@rakeshSgr yes

2024-07-08 12:22 UTC, rakeshSgr commented on src/api-doc/api-doc.yaml
> +      x-tags:
@sumanvpacewisdom why its added?

2024-07-08 13:01 UTC, merged