user service changes for SCP && Project service
ELEVATE-Project/user pull request #536
Opened 2024-07-11 05:47 UTC by VISHNUDAS-tunerlabs

elevate-project branch to develop merge

2024-07-15 09:31 UTC, adithyadinesh0412 commented on src/scripts/viewsScript.js
> +				'project_users_repeatable_view_job' + model,
@VISHNUDAS-tunerlabs  Can we add this ```project_users_repeatable_view_job``` as an env variable? So that , it won't break in the main user service?

2024-07-23 13:45 UTC, aks30 requested changes
Reviewed on 23 July

2024-07-23 13:45 UTC, aks30 commented on src/database/migrations/20240624153136-add-notification-template-for-elevate-projects.js
> +		const defaultOrgId = queryInterface.sequelize.options.defaultOrgId
@VISHNUDAS-tunerlabs can you confirm why we need this migration?

2024-07-23 13:45 UTC, aks30 commented on src/database/models/users.js
> +			location_ids: {
@VISHNUDAS-tunerlabs do we need this ? Can we just create entity types?

2024-07-23 13:45 UTC, aks30 commented on src/validators/v1/user-role.js
> +			.matches(/^[a-zA-Z_]+$/)
@VISHNUDAS-tunerlabs we should only create roles with lowercase right?

2024-07-23 13:45 UTC, aks30 commented on src/validators/v1/entity-type.js
> +			.withMessage('model_names must be in Session,MentorExtension,UserExtension, User')
User service is the only model name we should have

2024-07-25 04:25 UTC, VISHNUDAS-tunerlabs commented on src/constants/blacklistConfig.js
> -	create: ['id', 'status', 'type', 'created_by', 'updated_by'],
@aks30 we are expecting type to be passed with request body. in the entity validator not empty check is present for this field (type). This was causing issue. In existing code type has to be provided from req body while creating entity. So blacklisting that key is not correct

2024-07-25 04:26 UTC, VISHNUDAS-tunerlabs commented on src/controllers/v2/account.js
> + * name : account.js
@adithyadinesh0412 can you please comment on this ? added from SCP side

2024-07-25 04:26 UTC, VISHNUDAS-tunerlabs commented on src/controllers/v1/org-admin.js
> +	async updateUser(req) {
@adithyadinesh0412 can you please comment on this ? added from SCP side

2024-07-25 04:27 UTC, VISHNUDAS-tunerlabs commented on src/constants/common.js
> -	SESSION_MANAGER_ROLE: 'session_manager',
@adithyadinesh0412 can you please verify if this change came from SCP side?

2024-07-25 04:27 UTC, VISHNUDAS-tunerlabs commented on src/database/migrations/20240416185731-add-location-in-user-table.js
> +	async up(queryInterface, Sequelize) {
@adithyadinesh0412 can you please comment on this ? added from SCP side

2024-07-25 04:28 UTC, VISHNUDAS-tunerlabs commented on src/database/migrations/20240514113806-add-org-admin-permission-for-user-create.js
> +const getPermissionId = async (module, request_type, api_path) => {
@adithyadinesh0412 can you please comment on this ? added from SCP side

2024-07-25 04:30 UTC, VISHNUDAS-tunerlabs commented on src/database/migrations/20240624153136-add-notification-template-for-elevate-projects.js
> +		const defaultOrgId = queryInterface.sequelize.options.defaultOrgId
@aks30 Yes. There was a issue regarding email body showing mentorED related content in SCP and project services. So we have added new general email templates and updated the env varibles

2024-07-25 04:30 UTC, VISHNUDAS-tunerlabs commented on src/validators/v1/user-role.js
> +			.matches(/^[a-zA-Z_]+$/)
@adithyadinesh0412 can you please comment on this ? added from SCP side

2024-07-25 04:39 UTC, VISHNUDAS-tunerlabs commented on src/validators/v1/entity-type.js
> +			.withMessage('model_names must be in Session,MentorExtension,UserExtension, User')
@aks30 Yes. I think all other models are not required, was added by mistake. removed and updated the message

2024-07-25 06:50 UTC, adithyadinesh0412 commented on src/constants/common.js
> -	SESSION_MANAGER_ROLE: 'session_manager',
@VISHNUDAS-tunerlabs  This is a duplicate key in develop branch. hence we removed one. 
CC : @aks30

2024-07-25 06:51 UTC, adithyadinesh0412 commented on src/controllers/v2/account.js
> + * name : account.js
@VISHNUDAS-tunerlabs  We will remove this. We checked the interface service. interface is calling V1 controller only. So this can be removed.
CC : @aks30

2024-07-25 06:52 UTC, adithyadinesh0412 commented on src/controllers/v1/org-admin.js
> +	async updateUser(req) {
@aks30  , @VISHNUDAS-tunerlabs  : This was the requirement from the products. Org_admin should be able to add and revoke roles and organization to the user.

2024-07-25 06:56 UTC, adithyadinesh0412 commented on src/database/migrations/20240514113806-add-org-admin-permission-for-user-create.js
> +const getPermissionId = async (module, request_type, api_path) => {
@aks30  , @VISHNUDAS-tunerlabs  : In the user service only sys admin had the privilege to access user-roles related apis. (create, update). But for SCP , there was a requirement for org_admin to create custom user-roles for their organization, hence the permission for org_admin added here.

2024-07-25 06:57 UTC, adithyadinesh0412 commented on src/validators/v1/user-role.js
> +			.matches(/^[a-zA-Z_]+$/)
We will update this @aks30  , @VISHNUDAS-tunerlabs .
CC : @priyanka-TL

2024-07-25 07:14 UTC, VISHNUDAS-tunerlabs commented on src/database/models/users.js
> +			location_ids: {
@adithyadinesh0412 Please check this. added from SCP side

2024-07-28 18:18 UTC, priyanka-TL commented on src/api-doc/MentorED-Users DEV new.postman_collection.json
@adithyadinesh0412  Please check this postman collection, if this is not required please remove it. I have done the code changes

2024-08-06 11:04 UTC, aks30 requested changes
Reviewed on 6 Aug. Adithya and Vishnu to check and update the comments.

2024-08-06 11:04 UTC, aks30 commented on src/api-doc/MentorED-Users.postman_collection.json
> +		"_postman_id": "a4603eb4-a163-485a-aa40-a696066416a7",
@adithyadinesh0412 will remove the file from this PR raise a fresh PR to develop just for postman collection changes after this is merged.

2024-08-06 12:21 UTC, VISHNUDAS-tunerlabs commented on src/database/migrations/20240624153136-add-notification-template-for-elevate-projects.js
> +				body: '<p>Dear {name},</p> Welcome to {appName}.  We are excited to have you here!',
@aks30 sure. will resolve after discussion with products

2024-08-06 12:21 UTC, VISHNUDAS-tunerlabs commented on src/database/migrations/20240624153136-add-notification-template-for-elevate-projects.js
> +				body: "</div><div style='margin-top:20px;text-align:center;'><div>Regards,</div><div>Team Elevate </div><div style='margin-top:20px;color:#b13e33;text-align:center'><div>Note: Do not reply to thi
@aks30 sure. will resolve after discussion with products

2024-08-07 08:14 UTC, adithyadinesh0412 commented on src/services/account.js
> +			let roleQuery = {}
@aks30  Currently in validator we are validating this type as a mandatory field. so we didn't change the existing flow. 
If we have to make this change , we will need to check with mentoring team also to make sure that nothing will break from their side.
In mentoring they will have to explicitly pass type else they will receive all users irrespective of roles.

2024-08-07 09:50 UTC, adithyadinesh0412 commented on src/services/org-admin.js
> +	static async updateUser(userId, bodyData, tokenInformation) {
@aks30  Can we retain this API only for Admins? to add or remove roles / org from org admins. 

Org admins can use bulk upload to add users to their org and update user's roles. 

CC : @priyanka-TL

2024-08-07 10:16 UTC, merged