"user-role-read"
ELEVATE-Project/user pull request #542
Opened 2024-07-22 06:13 UTC by MallanagoudaB

2024-07-25 06:54 UTC, VISHNUDAS-tunerlabs requested changes
Finished First review at 12:30 Jul 25

2024-07-25 06:54 UTC, VISHNUDAS-tunerlabs commented on src/controllers/v1/user-role.js
> +	async read(req) {
@MallanagoudaB This api only read roles based on entity type right. So better to rename this api readUserRolesBasedOnEntityType. then you have to change the endpoint in entity-management service also. Update api documentation.

2024-07-25 06:54 UTC, VISHNUDAS-tunerlabs commented on src/controllers/v1/user-role.js
> +	async read(req) {
@MallanagoudaB validation is missing for this api. Please add required validation

2024-07-25 06:54 UTC, VISHNUDAS-tunerlabs commented on src/controllers/v1/user-role.js
> +	async read(req) {
@MallanagoudaB This endpoint should be public also. so that it can be called just like other api by passing user token. Make sure this api we can access like that. We might have to add this api to role-permission table. you can check with suman once

2024-07-25 06:54 UTC, VISHNUDAS-tunerlabs commented on src/controllers/v1/user-role.js
> +			const roleList = await roleService.readroleService(req.body)
@MallanagoudaB we can use readUserRolesBasedOnEntityType name for function name also

2024-07-25 06:54 UTC, VISHNUDAS-tunerlabs commented on src/services/user-role.js
> +	 * @param {Object} body - The request body containing the filter criteria.
@MallanagoudaB update function signature

2024-07-25 06:54 UTC, VISHNUDAS-tunerlabs commented on src/services/user-role.js
> +	static async readroleService(body) {
@MallanagoudaB Please change function name as per the suggestion

2024-07-25 06:54 UTC, VISHNUDAS-tunerlabs commented on src/services/user-role.js
> +			const filter = {
@MallanagoudaB we should optimise the query so that status should be active, and make sure the user role is not deleted

2024-07-25 06:54 UTC, VISHNUDAS-tunerlabs commented on src/services/user.js
> +		const roles = await userQueries.findOne({
@MallanagoudaB if we pass multiple ids does findOne return multiple data , even if valid data is present in DB? Please check that once.

2024-07-25 06:54 UTC, VISHNUDAS-tunerlabs commented on src/services/user.js
> +			if (bodyData.user_roles && bodyData.user_roles.length > 0) {
@MallanagoudaB Please add relevant comment for this if condition

2024-07-25 07:01 UTC, VISHNUDAS-tunerlabs commented on src/controllers/v1/user-role.js
> +	async read(req) {
@MallanagoudaB add this new api to api-doc and postman collection pls

2024-07-26 11:06 UTC, VISHNUDAS-tunerlabs requested changes
reviewed at 4:00 PM july 26

2024-07-26 11:06 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/MenterEd.postman_environment.json
>  			"value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Il9pZCI6IjYyODMyNTMxYTA1Y2JkNTdiMjczYWViYiIsImVtYWlsIjoiYW5raXQuc0BwYWNld2lzZG9tLmNvbSIsIm5hbWUiOiJBbmtpdCBTaGFodSIsImlzQU1lbnRvciI6ZmFsc
@MallanagoudaB we should not pass actual token here

2024-07-29 04:21 UTC, MallanagoudaB commented on src/api-doc/MenterEd.postman_environment.json
>  			"value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Il9pZCI6IjYyODMyNTZjNGRkMzI0NTdjYTU1Y2MwYSIsImVtYWlsIjoiYW5raXQuc2hhaHVAaG90bWFpbC5jb20iLCJuYW1lIjoiQW5raXQgU2hhaHUiLCJpc0FNZW50b3IiOnRyd
Should i make changes because it was there already i didnt add anything there.

2024-07-29 05:25 UTC, MallanagoudaB commented on src/services/user.js
> +				statusCode: httpStatusCode.unauthorized,
no @VISHNUDAS-tunerlabs  i checked the failureResponse in that file we have the same status code

2024-07-29 05:29 UTC, MallanagoudaB commented on src/api-doc/MenterEd.postman_environment.json
>  			"value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Il9pZCI6IjYyODMyNTMxYTA1Y2JkNTdiMjczYWViYiIsImVtYWlsIjoiYW5raXQuc0BwYWNld2lzZG9tLmNvbSIsIm5hbWUiOiJBbmtpdCBTaGFodSIsImlzQU1lbnRvciI6ZmFsc
OKay i didnt added this token it was there before let me change it then

2024-07-29 06:13 UTC, MallanagoudaB commented on src/controllers/v1/user-role.js
> +	async read(req) {
i asked nevil he said the current implementation will not supports that

2024-07-29 09:16 UTC, VISHNUDAS-tunerlabs requested changes

2024-07-29 09:16 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +        * Endpoint: ``` /user/v1/userRole/``readUserRolesBasedOnEntityType ```
@MallanagoudaB correct url

2024-07-29 09:16 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +        * The X-auth-token obtained from the login API is required in the
@MallanagoudaB  is it required for internal api

2024-07-29 09:47 UTC, VISHNUDAS-tunerlabs approved these changes
Reviewed on Jul 29 3:15 PM

2024-07-29 13:11 UTC, aks30 requested changes
Reviewed on 29 July - 
```
Generalise the name and function of the new API to be able to search and filter based on any key in meta.

"meta" : {
    "abce" : true,
    "entityTypes" : [
        {
            "id": 1,
            "type": "school"
        },
        {
            "id": 2,
            "type": "cluster"
        }
    ]
}
```

2024-08-01 10:36 UTC, aks30 requested changes
Reviewed on 1 Aug.

2024-08-01 10:36 UTC, aks30 commented on src/api-doc/MentorED-Users DEV new.postman_collection.json
> +		{
@MallanagoudaB These are not new APIs right then we don't need here.

2024-08-01 10:36 UTC, aks30 commented on src/services/user.js
> +		const filter = {
@MallanagoudaB Check with @nevil-mathew if this query is valid, @nevil-mathew if you can confirm query is optimised.

2024-08-01 11:42 UTC, nevil-mathew requested changes

2024-08-01 11:42 UTC, nevil-mathew commented on src/services/user.js
> +			},
Deleted flag is by default added to the query by sequelize, can you confirm once and remove this please.

2024-08-01 11:42 UTC, nevil-mathew commented on src/services/user.js
> +				[Op.in]: userRoleIds,
Using an array as the value will make Sequelize use the Op.in operator. So if userRoleIds is always an array, we don't need to explicitly use Op.in.

2024-08-01 13:36 UTC, nevil-mathew approved these changes
Reviewed and approved role query.

2024-08-01 16:42 UTC, merged