raw image added
ELEVATE-Project/user pull request #580
Opened 2024-10-30 14:25 UTC by rakeshSgr

2024-11-11 13:49 UTC, aks30 requested changes
Reviewed on 11 NOV

2024-11-11 13:49 UTC, aks30 commented on src/services/account.js
> +						user['image_cloud_path'] = user.image
@rakeshSgr verify if this works and image_cloud_path is not replaced with http URL

2024-11-11 13:49 UTC, aks30 commented on src/services/account.js
> +				users.map(async (user) => {
@rakeshSgr this can be optimised and used above

2024-11-15 12:09 UTC, rakeshSgr commented on src/services/account.js
> +						user['image_cloud_path'] = user.image
it won't replace

2024-11-19 06:29 UTC, merged